# Generated by Django 3.2 on 2021-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('nombreHomenajeado', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('barrioSector', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fechaEvento', models.CharField(max_length=20)),
                ('horaInicio', models.CharField(max_length=20)),
                ('numeroPaquete', models.CharField(max_length=10)),
                ('cantidadNinos', models.CharField(max_length=100)),
                ('rangoEdad', models.CharField(max_length=100)),
            ],
        ),
    ]
