# Generated by Django 3.2 on 2021-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_paquetes_numeropaquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetes',
            name='costoPaquete',
            field=models.CharField(max_length=100),
        ),
    ]
